/**
 * robotic-arm-server-api
 * The API for the Robotic Arm Server educational project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.4.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


#include <corvusoft/restbed/byte.hpp>
#include <corvusoft/restbed/string.hpp>
#include <corvusoft/restbed/settings.hpp>
#include <corvusoft/restbed/request.hpp>
#include <corvusoft/restbed/uri.hpp>
#include <boost/property_tree/ptree.hpp>
#include <boost/property_tree/json_parser.hpp>
#include <boost/lexical_cast.hpp>
#include <boost/algorithm/string.hpp>

#include "DeviceApi.h"

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

DeviceApiException::DeviceApiException(int status_code, std::string what)
  : m_status(status_code),
    m_what(what)
{

}
int DeviceApiException::getStatus() const
{
    return m_status;
}
const char* DeviceApiException::what() const noexcept
{
    return m_what.c_str();
}


template<class MODEL_T>
std::shared_ptr<MODEL_T> extractJsonModelBodyParam(const std::string& bodyContent)
{
    std::stringstream sstream(bodyContent);
    boost::property_tree::ptree pt;
    boost::property_tree::json_parser::read_json(sstream, pt);

    auto model = std::make_shared<MODEL_T>(pt);
    return model;
}

template<class MODEL_T>
std::vector<std::shared_ptr<MODEL_T>> extractJsonArrayBodyParam(const std::string& bodyContent)
{
    std::stringstream sstream(bodyContent);
    boost::property_tree::ptree pt;
    boost::property_tree::json_parser::read_json(sstream, pt);

    auto arrayRet = std::vector<std::shared_ptr<MODEL_T>>();
    for (const auto& child: pt) {
        arrayRet.emplace_back(std::make_shared<MODEL_T>(child.second));
    }
    return arrayRet;
}

template <class KEY_T, class VAL_T>
std::string convertMapResponse(const std::map<KEY_T, VAL_T>& map)
{
    boost::property_tree::ptree pt;
    for(const auto &kv: map) {
    pt.push_back(boost::property_tree::ptree::value_type(
        boost::lexical_cast<std::string>(kv.first),
        boost::property_tree::ptree(
        boost::lexical_cast<std::string>(kv.second))));
    }
    std::stringstream sstream;
    write_json(sstream, pt);
    std::string result = sstream.str();
    return result;
}

DeviceApiDeviceDeviceIdResource::DeviceApiDeviceDeviceIdResource(const std::string& context /* = "/artiomn/robotic_arm_server/1.0.0" */)
{
	this->set_path(context + "/device/{deviceId: .*}/");
	this->set_method_handler("GET",
		std::bind(&DeviceApiDeviceDeviceIdResource::handler_GET_internal, this,
			std::placeholders::_1));
	this->set_method_handler("DELETE",
		std::bind(&DeviceApiDeviceDeviceIdResource::handler_DELETE_internal, this,
			std::placeholders::_1));
}

DeviceApiDeviceDeviceIdResource::~DeviceApiDeviceDeviceIdResource()
{
}

std::pair<int, std::string> DeviceApiDeviceDeviceIdResource::handleDeviceApiException(const DeviceApiException& e)
{
    return std::make_pair<int, std::string>(e.getStatus(), e.what());
}

std::pair<int, std::string> DeviceApiDeviceDeviceIdResource::handleStdException(const std::exception& e)
{
    return std::make_pair<int, std::string>(500, e.what());
}

std::pair<int, std::string> DeviceApiDeviceDeviceIdResource::handleUnspecifiedException()
{
    return std::make_pair<int, std::string>(500, "Unknown exception occurred");
}

void DeviceApiDeviceDeviceIdResource::setResponseHeader(const std::shared_ptr<restbed::Session>& session, const std::string& header)
{
    session->set_header(header, "");
}

void DeviceApiDeviceDeviceIdResource::returnResponse(const std::shared_ptr<restbed::Session>& session, const int status, const std::string& result, const std::string& contentType)
{
    session->close(status, result, { {"Connection", "close"}, {"Content-Type", contentType} });
}

void DeviceApiDeviceDeviceIdResource::defaultSessionClose(const std::shared_ptr<restbed::Session>& session, const int status, const std::string& result)
{
    session->close(status, result, { {"Connection", "close"} });
}

void DeviceApiDeviceDeviceIdResource::handler_GET_internal(const std::shared_ptr<restbed::Session> session)
{
    const auto request = session->get_request();

    // Getting the path params
    const std::string deviceId = getPathParam_deviceId(request);



    int status_code = 500;
    std::shared_ptr<DeviceInfo> resultObject = std::make_shared<DeviceInfo>();
    std::string result = "";

    try {
        std::tie(status_code, resultObject) =
             handler_GET(deviceId);
    }
    catch(const DeviceApiException& e) {
        std::tie(status_code, result) = handleDeviceApiException(e);
    }
    catch(const std::exception& e) {
        std::tie(status_code, result) = handleStdException(e);
    }
    catch(...) {
        std::tie(status_code, result) = handleUnspecifiedException();
    }

    if (status_code == 200) {
        result = resultObject->toJsonString();

        const constexpr auto contentType = "application/json";
        returnResponse(session, 200, result.empty() ? "Device info" : result, contentType);
        return;
    }
    defaultSessionClose(session, status_code, result);
}

// x-extension
void DeviceApiDeviceDeviceIdResource::handler_DELETE_internal(const std::shared_ptr<restbed::Session> session) {

    const auto request = session->get_request();

    // Getting the path params
    const std::string deviceId = getPathParam_deviceId_x_extension(request);


    int status_code = 500;
    std::string result = "";

    try {
        status_code =
            handler_DELETE(deviceId);
    }
    catch(const DeviceApiException& e) {
        std::tie(status_code, result) = handleDeviceApiException(e);
    }
    catch(const std::exception& e) {
        std::tie(status_code, result) = handleStdException(e);
    }
    catch(...) {
        std::tie(status_code, result) = handleUnspecifiedException();
    }

    if (status_code == 200) {

        const constexpr auto contentType = "text/plain";
        returnResponse(session, 200, result.empty() ? "successfully unregistered device" : result, contentType);
        return;
    }
    defaultSessionClose(session, status_code, result);
}

std::pair<int, std::shared_ptr<DeviceInfo>> DeviceApiDeviceDeviceIdResource::handler_GET(
        std::string const & deviceId)
{
    throw DeviceApiException(501, "Not implemented");
}

int DeviceApiDeviceDeviceIdResource::handler_DELETE(
    std::string const & deviceId)
{
    throw DeviceApiException(501, "Not implemented");
}

std::string DeviceApiDeviceDeviceIdResource::extractBodyContent(const std::shared_ptr<restbed::Session>& session) {
  const auto request = session->get_request();
  int content_length = request->get_header("Content-Length", 0);
  std::string bodyContent;
  session->fetch(content_length,
                 [&bodyContent](const std::shared_ptr<restbed::Session> session,
                                const restbed::Bytes &body) {
                   bodyContent = restbed::String::format(
                       "%.*s\n", (int)body.size(), body.data());
                 });
  return bodyContent;
}

DeviceApi::DeviceApi(std::shared_ptr<restbed::Service> const& restbedService)
: m_service(restbedService)
{
}

DeviceApi::~DeviceApi() {}

void DeviceApi::setDeviceApiDeviceDeviceIdResource(std::shared_ptr<DeviceApiDeviceDeviceIdResource> spDeviceApiDeviceDeviceIdResource) {
    m_spDeviceApiDeviceDeviceIdResource = spDeviceApiDeviceDeviceIdResource;
    m_service->publish(m_spDeviceApiDeviceDeviceIdResource);
}


void DeviceApi::publishDefaultResources() {
    if (!m_spDeviceApiDeviceDeviceIdResource) {
        setDeviceApiDeviceDeviceIdResource(std::make_shared<DeviceApiDeviceDeviceIdResource>());
    }
}

std::shared_ptr<restbed::Service> DeviceApi::service() {
    return m_service;
}


}
}
}
}

