/**
 * robotic-arm-server-api
 * The API for the Robotic Arm Server educational project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.4.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


#include <corvusoft/restbed/byte.hpp>
#include <corvusoft/restbed/string.hpp>
#include <corvusoft/restbed/settings.hpp>
#include <corvusoft/restbed/request.hpp>
#include <corvusoft/restbed/uri.hpp>
#include <boost/property_tree/ptree.hpp>
#include <boost/property_tree/json_parser.hpp>
#include <boost/lexical_cast.hpp>
#include <boost/algorithm/string.hpp>

#include "DevicesApi.h"

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

DevicesApiException::DevicesApiException(int status_code, std::string what)
  : m_status(status_code),
    m_what(what)
{

}
int DevicesApiException::getStatus() const
{
    return m_status;
}
const char* DevicesApiException::what() const noexcept
{
    return m_what.c_str();
}


template<class MODEL_T>
std::shared_ptr<MODEL_T> extractJsonModelBodyParam(const std::string& bodyContent)
{
    std::stringstream sstream(bodyContent);
    boost::property_tree::ptree pt;
    boost::property_tree::json_parser::read_json(sstream, pt);

    auto model = std::make_shared<MODEL_T>(pt);
    return model;
}

template<class MODEL_T>
std::vector<std::shared_ptr<MODEL_T>> extractJsonArrayBodyParam(const std::string& bodyContent)
{
    std::stringstream sstream(bodyContent);
    boost::property_tree::ptree pt;
    boost::property_tree::json_parser::read_json(sstream, pt);

    auto arrayRet = std::vector<std::shared_ptr<MODEL_T>>();
    for (const auto& child: pt) {
        arrayRet.emplace_back(std::make_shared<MODEL_T>(child.second));
    }
    return arrayRet;
}

template <class KEY_T, class VAL_T>
std::string convertMapResponse(const std::map<KEY_T, VAL_T>& map)
{
    boost::property_tree::ptree pt;
    for(const auto &kv: map) {
    pt.push_back(boost::property_tree::ptree::value_type(
        boost::lexical_cast<std::string>(kv.first),
        boost::property_tree::ptree(
        boost::lexical_cast<std::string>(kv.second))));
    }
    std::stringstream sstream;
    write_json(sstream, pt);
    std::string result = sstream.str();
    return result;
}

DevicesApiDevicesResource::DevicesApiDevicesResource(const std::string& context /* = "/artiomn/robotic_arm_server/1.0.0" */)
{
	this->set_path(context + "/devices/");
	this->set_method_handler("GET",
		std::bind(&DevicesApiDevicesResource::handler_GET_internal, this,
			std::placeholders::_1));
	this->set_method_handler("POST",
		std::bind(&DevicesApiDevicesResource::handler_POST_internal, this,
			std::placeholders::_1));
}

DevicesApiDevicesResource::~DevicesApiDevicesResource()
{
}

std::pair<int, std::string> DevicesApiDevicesResource::handleDevicesApiException(const DevicesApiException& e)
{
    return std::make_pair<int, std::string>(e.getStatus(), e.what());
}

std::pair<int, std::string> DevicesApiDevicesResource::handleStdException(const std::exception& e)
{
    return std::make_pair<int, std::string>(500, e.what());
}

std::pair<int, std::string> DevicesApiDevicesResource::handleUnspecifiedException()
{
    return std::make_pair<int, std::string>(500, "Unknown exception occurred");
}

void DevicesApiDevicesResource::setResponseHeader(const std::shared_ptr<restbed::Session>& session, const std::string& header)
{
    session->set_header(header, "");
}

void DevicesApiDevicesResource::returnResponse(const std::shared_ptr<restbed::Session>& session, const int status, const std::string& result, const std::string& contentType)
{
    session->close(status, result, { {"Connection", "close"}, {"Content-Type", contentType} });
}

void DevicesApiDevicesResource::defaultSessionClose(const std::shared_ptr<restbed::Session>& session, const int status, const std::string& result)
{
    session->close(status, result, { {"Connection", "close"} });
}

void DevicesApiDevicesResource::handler_GET_internal(const std::shared_ptr<restbed::Session> session)
{
    const auto request = session->get_request();


    // Getting the query params
    const int32_t skip = getQueryParam_skip(request);
    const int32_t limit = getQueryParam_limit(request);


    int status_code = 500;
    std::vector<std::string> resultObject = std::vector<std::string>();
    std::string result = "";

    try {
        std::tie(status_code, resultObject) =
             handler_GET(skip, limit);
    }
    catch(const DevicesApiException& e) {
        std::tie(status_code, result) = handleDevicesApiException(e);
    }
    catch(const std::exception& e) {
        std::tie(status_code, result) = handleStdException(e);
    }
    catch(...) {
        std::tie(status_code, result) = handleUnspecifiedException();
    }

    if (status_code == 200) {
        if (result.empty() && !resultObject.empty())
        {
            result = "[";
            for (const auto &r : resultObject) result += "\"" + r + "\", ";
            // Remove last 2 characters (", ").
            result.resize(result.size() - 2);
            result += "]";
        }

        const constexpr auto contentType = "application/json";
        returnResponse(session, 200, result.empty() ? "All the devices" : result, contentType);
        return;
    }
    defaultSessionClose(session, status_code, result);
}

// x-extension
void DevicesApiDevicesResource::handler_POST_internal(const std::shared_ptr<restbed::Session> session) {

    const auto request = session->get_request();
    std::string bodyContent = extractBodyContent(session);

    // body params or form params here from the body content string
    auto deviceRegistrationInfo = extractJsonModelBodyParam<DeviceRegistrationInfo>(bodyContent);


    int status_code = 500;
    std::string result = "";

    try {
        status_code =
            handler_POST(deviceRegistrationInfo);
    }
    catch(const DevicesApiException& e) {
        std::tie(status_code, result) = handleDevicesApiException(e);
    }
    catch(const std::exception& e) {
        std::tie(status_code, result) = handleStdException(e);
    }
    catch(...) {
        std::tie(status_code, result) = handleUnspecifiedException();
    }

    if (status_code == 200) {

        const constexpr auto contentType = "text/plain";
        returnResponse(session, 200, result.empty() ? "successfully registered device" : result, contentType);
        return;
    }
    defaultSessionClose(session, status_code, result);
}

std::pair<int, std::vector<std::string>> DevicesApiDevicesResource::handler_GET(
        int32_t const & skip, int32_t const & limit)
{
    throw DevicesApiException(501, "Not implemented");
}

int DevicesApiDevicesResource::handler_POST(
    std::shared_ptr<DeviceRegistrationInfo> const & deviceRegistrationInfo)
{
    throw DevicesApiException(501, "Not implemented");
}

std::string DevicesApiDevicesResource::extractBodyContent(const std::shared_ptr<restbed::Session>& session) {
  const auto request = session->get_request();
  int content_length = request->get_header("Content-Length", 0);
  std::string bodyContent;
  session->fetch(content_length,
                 [&bodyContent](const std::shared_ptr<restbed::Session> session,
                                const restbed::Bytes &body) {
                   bodyContent = restbed::String::format(
                       "%.*s\n", (int)body.size(), body.data());
                 });
  return bodyContent;
}

DevicesApi::DevicesApi(std::shared_ptr<restbed::Service> const& restbedService)
: m_service(restbedService)
{
}

DevicesApi::~DevicesApi() {}

void DevicesApi::setDevicesApiDevicesResource(std::shared_ptr<DevicesApiDevicesResource> spDevicesApiDevicesResource) {
    m_spDevicesApiDevicesResource = spDevicesApiDevicesResource;
    m_service->publish(m_spDevicesApiDevicesResource);
}


void DevicesApi::publishDefaultResources() {
    if (!m_spDevicesApiDevicesResource) {
        setDevicesApiDevicesResource(std::make_shared<DevicesApiDevicesResource>());
    }
}

std::shared_ptr<restbed::Service> DevicesApi::service() {
    return m_service;
}


}
}
}
}

