/**
 * robotic-arm-server-api
 * The API for the Robotic Arm Server educational project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.4.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * DevicesApi.h
 *
 * 
 */

#ifndef DevicesApi_H_
#define DevicesApi_H_


#include <memory>
#include <utility>
#include <exception>

#include <corvusoft/restbed/session.hpp>
#include <corvusoft/restbed/resource.hpp>
#include <corvusoft/restbed/request.hpp>
#include <corvusoft/restbed/service.hpp>
#include <corvusoft/restbed/settings.hpp>

#include "DeviceRegistrationInfo.h"
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

///
/// Exception to flag problems in the handlers
///
class  DevicesApiException: public std::exception
{
public:
    DevicesApiException(int status_code, std::string what);

    int getStatus() const;
    const char* what() const noexcept override;

private:
    int m_status;
    std::string m_what;
};

/// <summary>
/// 
/// </summary>
/// <remarks>
/// returns all registered devices
/// </remarks>
class  DevicesApiDevicesResource: public restbed::Resource
{
public:
    DevicesApiDevicesResource(const std::string& context = "/artiomn/robotic_arm_server/1.0.0");
    virtual ~DevicesApiDevicesResource();

protected:
    //////////////////////////////////////////////////////////
    // Override these to implement the server functionality //
    //////////////////////////////////////////////////////////

    virtual std::pair<int, std::vector<std::string>> handler_GET(
        int32_t const & skip, int32_t const & limit);

    virtual int handler_POST(
        std::shared_ptr<DeviceRegistrationInfo> const & deviceRegistrationInfo);

protected:
    //////////////////////////////////////
    // Override these for customization //
    //////////////////////////////////////

    virtual std::string extractBodyContent(const std::shared_ptr<restbed::Session>& session);

    virtual int32_t getQueryParam_skip(const std::shared_ptr<const restbed::Request>& request)
    {
        return request->get_query_parameter("skip", 0);
    }

    virtual int32_t getQueryParam_limit(const std::shared_ptr<const restbed::Request>& request)
    {
        return request->get_query_parameter("limit", 0);
    }



    virtual std::pair<int, std::string> handleDevicesApiException(const DevicesApiException& e);
    virtual std::pair<int, std::string> handleStdException(const std::exception& e);
    virtual std::pair<int, std::string> handleUnspecifiedException();

    virtual void setResponseHeader(const std::shared_ptr<restbed::Session>& session,
        const std::string& header);


    virtual void returnResponse(const std::shared_ptr<restbed::Session>& session,
        const int status, const std::string& result, const std::string& contentType);
    virtual void defaultSessionClose(const std::shared_ptr<restbed::Session>& session,
        const int status, const std::string& result);

private:
    void handler_GET_internal(const std::shared_ptr<restbed::Session> session);
    void handler_POST_internal(const std::shared_ptr<restbed::Session> session);
};



//
// The restbed service to actually implement the REST server
//
class  DevicesApi
{
public:
    explicit DevicesApi(std::shared_ptr<restbed::Service> const& restbedService);
	virtual ~DevicesApi();

    virtual void setDevicesApiDevicesResource(std::shared_ptr<DevicesApiDevicesResource> spDevicesApiDevicesResource);

    virtual void publishDefaultResources();

    virtual std::shared_ptr<restbed::Service> service();

protected:
	std::shared_ptr<DevicesApiDevicesResource> m_spDevicesApiDevicesResource;

private:
    std::shared_ptr<restbed::Service> m_service;
};


}
}
}
}

#endif /* DevicesApi_H_ */

