/**
 * robotic-arm-server-api
 * The API for the Robotic Arm Server educational project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.4.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "DeviceInfo.h"

#include <string>
#include <vector>
#include <sstream>
#include <stdexcept>
#include <boost/property_tree/ptree.hpp>
#include <boost/property_tree/json_parser.hpp>
#include <boost/foreach.hpp>

using boost::property_tree::ptree;
using boost::property_tree::read_json;
using boost::property_tree::write_json;

namespace org {
namespace openapitools {
namespace server {
namespace model {

DeviceInfo::DeviceInfo(boost::property_tree::ptree const& pt)
{
        fromPropertyTree(pt);
}

std::string DeviceInfo::toJsonString(bool prettyJson /* = false */)
{
    return toJsonString_internal(prettyJson);
}

void DeviceInfo::fromJsonString(std::string const& jsonString)
{
    fromJsonString_internal(jsonString);
}

boost::property_tree::ptree DeviceInfo::toPropertyTree()
{
    return toPropertyTree_internal();
}

void DeviceInfo::fromPropertyTree(boost::property_tree::ptree const& pt)
{
    fromPropertyTree_internal(pt);
}

std::string DeviceInfo::toJsonString_internal(bool prettyJson)
{
	std::stringstream ss;
	write_json(ss, this->toPropertyTree(), prettyJson);
	return ss.str();
}

void DeviceInfo::fromJsonString_internal(std::string const& jsonString)
{
	std::stringstream ss(jsonString);
	ptree pt;
	read_json(ss,pt);
	this->fromPropertyTree(pt);
}

ptree DeviceInfo::toPropertyTree_internal()
{
	ptree pt;
	ptree tmp_node;
	pt.put("name", m_Name);
    BOOST_FOREACH(auto& update, m_State->toPropertyTree())
    {
        pt.put_child(update.first, update.second);
    }
	return pt;
}

void DeviceInfo::fromPropertyTree_internal(ptree const &pt)
{
	ptree tmp_node;
	m_Name = pt.get("name", "");
	m_State->fromPropertyTree(pt);
}

std::string DeviceInfo::getName() const
{
    return m_Name;
}

void DeviceInfo::setName(std::string value)
{
	m_Name = value;
}
std::shared_ptr<DeviceState> DeviceInfo::getState() const
{
    return m_State;
}

void DeviceInfo::setState(std::shared_ptr<DeviceState> value)
{
	m_State = value;
}

std::vector<DeviceInfo> createDeviceInfoVectorFromJsonString(const std::string& json)
{
    std::stringstream sstream(json);
    boost::property_tree::ptree pt;
    boost::property_tree::json_parser::read_json(sstream,pt);

    auto vec = std::vector<DeviceInfo>();
    for (const auto& child: pt) {
        vec.emplace_back(DeviceInfo(child.second));
    }

    return vec;
}

}
}
}
}

