/**
 * robotic-arm-server-api
 * The API for the Robotic Arm Server educational project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.4.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * DeviceState.h
 *
 * 
 */

#ifndef DeviceState_H_
#define DeviceState_H_



#include <memory>
#include <vector>
#include <boost/property_tree/ptree.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  DeviceState 
{
public:
    DeviceState() = default;
    explicit DeviceState(boost::property_tree::ptree const& pt);
    virtual ~DeviceState() = default;

    std::string toJsonString(bool prettyJson = false);
    void fromJsonString(std::string const& jsonString);
    boost::property_tree::ptree toPropertyTree();
    void fromPropertyTree(boost::property_tree::ptree const& pt);

    /////////////////////////////////////////////
    /// DeviceState members

protected:
    //////////////////////////////////////
    // Override these for customization //
    //////////////////////////////////////

    virtual std::string toJsonString_internal(bool prettyJson = false);
    virtual void fromJsonString_internal(std::string const& jsonString);
    virtual boost::property_tree::ptree toPropertyTree_internal();
    virtual void fromPropertyTree_internal(boost::property_tree::ptree const& pt);


protected:
    std::string m_Value;
};

std::vector<DeviceState> createDeviceStateVectorFromJsonString(const std::string& json);

}
}
}
}

#endif /* DeviceState_H_ */
