/**
 * robotic-arm-server-api
 * The API for the Robotic Arm Server educational project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.4.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "DeviceRegistrationInfo.h"

#include <string>
#include <vector>
#include <sstream>
#include <stdexcept>
#include <boost/property_tree/ptree.hpp>
#include <boost/property_tree/json_parser.hpp>

using boost::property_tree::ptree;
using boost::property_tree::read_json;
using boost::property_tree::write_json;

namespace org {
namespace openapitools {
namespace server {
namespace model {

DeviceRegistrationInfo::DeviceRegistrationInfo(boost::property_tree::ptree const& pt)
{
        fromPropertyTree(pt);
}

std::string DeviceRegistrationInfo::toJsonString(bool prettyJson /* = false */)
{
    return toJsonString_internal(prettyJson);
}

void DeviceRegistrationInfo::fromJsonString(std::string const& jsonString)
{
    fromJsonString_internal(jsonString);
}

boost::property_tree::ptree DeviceRegistrationInfo::toPropertyTree()
{
    return toPropertyTree_internal();
}

void DeviceRegistrationInfo::fromPropertyTree(boost::property_tree::ptree const& pt)
{
    fromPropertyTree_internal(pt);
}

std::string DeviceRegistrationInfo::toJsonString_internal(bool prettyJson)
{
	std::stringstream ss;
	write_json(ss, this->toPropertyTree(), prettyJson);
	return ss.str();
}

void DeviceRegistrationInfo::fromJsonString_internal(std::string const& jsonString)
{
	std::stringstream ss(jsonString);
	ptree pt;
	read_json(ss,pt);
	this->fromPropertyTree(pt);
}

ptree DeviceRegistrationInfo::toPropertyTree_internal()
{
	ptree pt;
	ptree tmp_node;
	pt.put("name", m_Name);
	pt.put("id", m_Id);
	return pt;
}

void DeviceRegistrationInfo::fromPropertyTree_internal(ptree const &pt)
{
	ptree tmp_node;
	m_Name = pt.get("name", "");
	m_Id = pt.get("id", "");
}

std::string DeviceRegistrationInfo::getName() const
{
    return m_Name;
}

void DeviceRegistrationInfo::setName(std::string value)
{
	m_Name = value;
}
std::string DeviceRegistrationInfo::getId() const
{
    return m_Id;
}

void DeviceRegistrationInfo::setId(std::string value)
{
	m_Id = value;
}

std::vector<DeviceRegistrationInfo> createDeviceRegistrationInfoVectorFromJsonString(const std::string& json)
{
    std::stringstream sstream(json);
    boost::property_tree::ptree pt;
    boost::property_tree::json_parser::read_json(sstream,pt);

    auto vec = std::vector<DeviceRegistrationInfo>();
    for (const auto& child: pt) {
        vec.emplace_back(DeviceRegistrationInfo(child.second));
    }

    return vec;
}

}
}
}
}

