/**
 * robotic-arm-server-api
 * The API for the Robotic Arm Server educational project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.4.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "DeviceState.h"

#include <string>
#include <vector>
#include <sstream>
#include <stdexcept>
#include <boost/property_tree/ptree.hpp>
#include <boost/property_tree/json_parser.hpp>

using boost::property_tree::ptree;
using boost::property_tree::read_json;
using boost::property_tree::write_json;

namespace org {
namespace openapitools {
namespace server {
namespace model {

DeviceState::DeviceState(boost::property_tree::ptree const& pt)
{
        fromPropertyTree(pt);
}

std::string DeviceState::toJsonString(bool prettyJson /* = false */)
{
    return toJsonString_internal(prettyJson);
}

void DeviceState::fromJsonString(std::string const& jsonString)
{
    fromJsonString_internal(jsonString);
}

boost::property_tree::ptree DeviceState::toPropertyTree()
{
    return toPropertyTree_internal();
}

void DeviceState::fromPropertyTree(boost::property_tree::ptree const& pt)
{
    fromPropertyTree_internal(pt);
}

std::string DeviceState::toJsonString_internal(bool prettyJson)
{
	std::stringstream ss;
	write_json(ss, this->toPropertyTree(), prettyJson);
	return ss.str();
}

void DeviceState::fromJsonString_internal(std::string const& jsonString)
{
	std::stringstream ss(jsonString);
	ptree pt;
	read_json(ss,pt);
	this->fromPropertyTree(pt);
}

ptree DeviceState::toPropertyTree_internal()
{
	ptree pt;
	pt.put("state", m_Value);
	return pt;
}

void DeviceState::fromPropertyTree_internal(ptree const &pt)
{
	m_Value = pt.get("state", "unknown");
}


std::vector<DeviceState> createDeviceStateVectorFromJsonString(const std::string& json)
{
    std::stringstream sstream(json);
    boost::property_tree::ptree pt;
    boost::property_tree::json_parser::read_json(sstream,pt);

    auto vec = std::vector<DeviceState>();
    for (const auto& child: pt) {
        vec.emplace_back(DeviceState(child.second));
    }

    return vec;
}

}
}
}
}

