/**
 * robotic-arm-server-api
 * The API for the Robotic Arm Server educational project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.4.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * DeviceInfo.h
 *
 * 
 */

#ifndef DeviceInfo_H_
#define DeviceInfo_H_



#include <string>
#include "DeviceState.h"
#include <memory>
#include <vector>
#include <boost/property_tree/ptree.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  DeviceInfo 
{
public:
    DeviceInfo() = default;
    explicit DeviceInfo(boost::property_tree::ptree const& pt);
    virtual ~DeviceInfo() = default;

    std::string toJsonString(bool prettyJson = false);
    void fromJsonString(std::string const& jsonString);
    boost::property_tree::ptree toPropertyTree();
    void fromPropertyTree(boost::property_tree::ptree const& pt);

    /////////////////////////////////////////////
    /// DeviceInfo members

    /// <summary>
    /// 
    /// </summary>
    std::string getName() const;
    void setName(std::string value);

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<DeviceState> getState() const;
    void setState(std::shared_ptr<DeviceState> value);

protected:
    //////////////////////////////////////
    // Override these for customization //
    //////////////////////////////////////

    virtual std::string toJsonString_internal(bool prettyJson = false);
    virtual void fromJsonString_internal(std::string const& jsonString);
    virtual boost::property_tree::ptree toPropertyTree_internal();
    virtual void fromPropertyTree_internal(boost::property_tree::ptree const& pt);


protected:
    std::string m_Name = "";
    std::shared_ptr<DeviceState> m_State = std::make_shared<DeviceState>();
};

std::vector<DeviceInfo> createDeviceInfoVectorFromJsonString(const std::string& json);

}
}
}
}

#endif /* DeviceInfo_H_ */
